// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class FitnessCoaching {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.ScriptManager ScriptManager2;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.DropDownList nutrition_status;
	
	protected System.Web.UI.WebControls.CheckBox nutrition_dp;
	
	protected System.Web.UI.WebControls.DropDownList fitness_status;
	
	protected System.Web.UI.WebControls.CheckBox fitness_dp;
	
	protected System.Web.UI.WebControls.DropDownList weight_status;
	
	protected System.Web.UI.WebControls.CheckBox weight_dp;
	
	protected System.Web.UI.WebControls.DropDownList muscle_status;
	
	protected System.Web.UI.WebControls.CheckBox muscle_dp;
	
	protected System.Web.UI.WebControls.DropDownList stress_status;
	
	protected System.Web.UI.WebControls.CheckBox stress_dp;
	
	protected System.Web.UI.WebControls.DropDownList diabetes_status;
	
	protected System.Web.UI.WebControls.CheckBox diabetes_dp;
	
	protected System.Web.UI.WebControls.DropDownList sleeping_status;
	
	protected System.Web.UI.WebControls.CheckBox sleeping_dp;
	
	protected System.Web.UI.WebControls.TextBox addictive_text;
	
	protected System.Web.UI.WebControls.DropDownList addictive_status;
	
	protected System.Web.UI.WebControls.CheckBox Addictive_dp;
	
	protected System.Web.UI.WebControls.DropDownList cardio_status;
	
	protected System.Web.UI.WebControls.CheckBox Cardiovascular_dp;
	
	protected System.Web.UI.WebControls.DropDownList cancer_status;
	
	protected System.Web.UI.WebControls.CheckBox Cancer_dp;
	
	protected System.Web.UI.WebControls.DropDownList lab_status;
	
	protected System.Web.UI.WebControls.CheckBox Labassessment_dp;
	
	protected System.Web.UI.WebControls.TextBox notes;
	
	protected System.Web.UI.WebControls.Button Button1;
}
