// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class HealthCoaching {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.HtmlControls.HtmlForm sub;
	
	protected System.Web.UI.ScriptManager ScriptManager2;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.CheckBox headache_past;
	
	protected System.Web.UI.WebControls.CheckBox headache_current;
	
	protected System.Web.UI.WebControls.CheckBox headache_treatment;
	
	protected System.Web.UI.WebControls.CheckBox Neckpain_past;
	
	protected System.Web.UI.WebControls.CheckBox Neckpain_current;
	
	protected System.Web.UI.WebControls.CheckBox Neckpain_treatment;
	
	protected System.Web.UI.WebControls.CheckBox arms_past;
	
	protected System.Web.UI.WebControls.CheckBox arms_current;
	
	protected System.Web.UI.WebControls.CheckBox arms_treatment;
	
	protected System.Web.UI.WebControls.CheckBox shoulder_past;
	
	protected System.Web.UI.WebControls.CheckBox shoulder_current;
	
	protected System.Web.UI.WebControls.CheckBox shoulder_treatment;
	
	protected System.Web.UI.WebControls.CheckBox lowback_past;
	
	protected System.Web.UI.WebControls.CheckBox lowback_current;
	
	protected System.Web.UI.WebControls.CheckBox lowback_treatment;
	
	protected System.Web.UI.WebControls.CheckBox leg_past;
	
	protected System.Web.UI.WebControls.CheckBox leg_current;
	
	protected System.Web.UI.WebControls.CheckBox leg_treatment;
	
	protected System.Web.UI.WebControls.TextBox health_comments;
	
	protected System.Web.UI.WebControls.Button Button1;
}
