// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Loggings {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content3;
	
	protected System.Web.UI.WebControls.ValidationSummary Validationsum1;
	
	protected System.Web.UI.WebControls.TextBox Height_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator requiredFieldValidationdate;
	
	protected System.Web.UI.WebControls.TextBox Weight_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
	
	protected System.Web.UI.WebControls.TextBox BMI_Text;
	
	protected System.Web.UI.WebControls.TextBox BP_1;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
	
	protected System.Web.UI.WebControls.TextBox BP_2;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
	
	protected System.Web.UI.WebControls.TextBox Heartrate_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
	
	protected System.Web.UI.WebControls.TextBox oxygen_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
	
	protected System.Web.UI.WebControls.TextBox skin1_text;
	
	protected System.Web.UI.WebControls.TextBox skin2_text;
	
	protected System.Web.UI.WebControls.TextBox skin3_text;
	
	protected System.Web.UI.WebControls.TextBox Hipflex_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
	
	protected System.Web.UI.WebControls.TextBox Hipext_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;
	
	protected System.Web.UI.WebControls.TextBox Lside_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator8;
	
	protected System.Web.UI.WebControls.TextBox Rside_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator9;
	
	protected System.Web.UI.WebControls.TextBox curlup_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator10;
	
	protected System.Web.UI.WebControls.TextBox Pushup_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator11;
	
	protected System.Web.UI.WebControls.TextBox Gripleft_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator12;
	
	protected System.Web.UI.WebControls.TextBox Gripright_text;
	
	protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator13;
	
	protected System.Web.UI.WebControls.DropDownList armraise;
	
	protected System.Web.UI.WebControls.DropDownList KneeBend;
	
	protected System.Web.UI.WebControls.TextBox sit1_text;
	
	protected System.Web.UI.WebControls.TextBox sit2_text;
	
	protected System.Web.UI.WebControls.TextBox sit3_text;
	
	protected System.Web.UI.WebControls.TextBox note_text;
	
	protected System.Web.UI.WebControls.Button Fitnesstesting_save;
}
