// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class PARQ {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.ScriptManager ScriptManager2;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.Button Button3;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList2;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList3;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList4;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList5;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList6;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList7;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList8;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList9;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList10;
	
	protected System.Web.UI.WebControls.RadioButtonList RadioButtonList11;
	
	protected System.Web.UI.WebControls.Button Button1;
}
