// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Prescription {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.Content Content2;
	
	protected System.Web.UI.HtmlControls.HtmlForm sub;
	
	protected System.Web.UI.ScriptManager ScriptManager2;
	
	protected System.Web.UI.WebControls.Panel Panel2;
	
	protected System.Web.UI.WebControls.Label probName;

    protected System.Web.UI.WebControls.TextBox breakfasttime;

    protected System.Web.UI.WebControls.TextBox breakfastsnacktime;

    protected System.Web.UI.WebControls.TextBox lunchtime;

    protected System.Web.UI.WebControls.TextBox lunchsnacktime;

    protected System.Web.UI.WebControls.TextBox dinnertime;

    protected System.Web.UI.WebControls.TextBox dinnersnacktime;

    protected System.Web.UI.WebControls.TextBox txtCashAmt;

    protected System.Web.UI.WebControls.TextBox txtCashAmt2;

    protected System.Web.UI.WebControls.TextBox Mondaybreakfast;

    protected System.Web.UI.WebControls.TextBox mondaybreakfastsnack;

    protected System.Web.UI.WebControls.TextBox mondaylunch;

    protected System.Web.UI.WebControls.TextBox mondaylunchsnack;

    protected System.Web.UI.WebControls.TextBox mondaydinner;

    protected System.Web.UI.WebControls.TextBox mondaydinnersnack;

    protected System.Web.UI.WebControls.TextBox tuesdaybreak;

    protected System.Web.UI.WebControls.TextBox tuesdaybreaksnack;

    protected System.Web.UI.WebControls.TextBox tuesdaylunch;

    protected System.Web.UI.WebControls.TextBox tuesdaylunchsnack;

    protected System.Web.UI.WebControls.TextBox tuesdaydinner;

    protected System.Web.UI.WebControls.TextBox tuesdaydinnersnack;

    protected System.Web.UI.WebControls.TextBox wednesdaybreak;

    protected System.Web.UI.WebControls.TextBox wednesdaybreaksnack;

    protected System.Web.UI.WebControls.TextBox wednesdaylunch;

    protected System.Web.UI.WebControls.TextBox wednesdaylunchsnack;

    protected System.Web.UI.WebControls.TextBox wednesdaydinner;

    protected System.Web.UI.WebControls.TextBox wednesdaydinnersnack;

    protected System.Web.UI.WebControls.TextBox thursdaybreak;

    protected System.Web.UI.WebControls.TextBox thursdaybreaksnack;

    protected System.Web.UI.WebControls.TextBox thursdaylunch;

    protected System.Web.UI.WebControls.TextBox thursdaylunchsnack;

    protected System.Web.UI.WebControls.TextBox thursdaydinner;

    protected System.Web.UI.WebControls.TextBox thursdaydinnersnack;

    protected System.Web.UI.WebControls.TextBox fridaybreak;

    protected System.Web.UI.WebControls.TextBox fridaybreaksnack;

    protected System.Web.UI.WebControls.TextBox fridaylunch;

    protected System.Web.UI.WebControls.TextBox fridaylunchsnack;

    protected System.Web.UI.WebControls.TextBox fridaydinner;

    protected System.Web.UI.WebControls.TextBox fridaydinnersnack;

    protected System.Web.UI.WebControls.TextBox satbreak;

    protected System.Web.UI.WebControls.TextBox satbreaksnack;

    protected System.Web.UI.WebControls.TextBox satlunch;

    protected System.Web.UI.WebControls.TextBox satlunchsnack;

    protected System.Web.UI.WebControls.TextBox satdinner;

    protected System.Web.UI.WebControls.TextBox satdinnersnack;

    protected System.Web.UI.WebControls.TextBox sundaybreak;

    protected System.Web.UI.WebControls.TextBox sundbreaksnack;

    protected System.Web.UI.WebControls.TextBox sundaylunch;

    protected System.Web.UI.WebControls.TextBox sundaylunchsnack;

    protected System.Web.UI.WebControls.TextBox sundaydinner;

    protected System.Web.UI.WebControls.TextBox sundaydinnersnack;

    protected System.Web.UI.WebControls.Label minigoal;

    protected System.Web.UI.WebControls.Label minigoaldate;

    protected System.Web.UI.WebControls.Label goal;

    protected System.Web.UI.WebControls.Label goalsatrtdate;

    protected System.Web.UI.WebControls.Label goalenddate;

}
